### ISSUE TITLE
Tabs?

### ISSUE THREAD

**Issue by ZaneHannanAU** [dbartholomae/stylus-material#1]
In the NPM package it has tabs.styl, but in the docs, git repo etc it doesn't seem to exist.

Is there a notable issue with it or ?

**Comment by dbartholomae** [comment]
Thanks for pointing this out! It seems that a purely experimental file found its way into the NPM package, most likely because it wasn't even added to git. If you are interested in adding tabs, the file might be a start, though.

**Comment by ZaneHannanAU** [comment]
Currently I use these:

```stylus
nav
	sm-tabs(
		nav-height,
		$primary-color,
		$accent-color
		)
	sm-z 1
	position fixed
	top 0
	left 0
	z-index 3
	>*
		min-width 99px
		&:hover
		&:focus
		&:active
			border-bottom 1px solid
	+*
		margin-top (nav-height)
	~*
		.focusable
			margin-top -(nav-height)
			padding-top (nav-height)
```

where nav-height is 3rem

If you can add this into the next release (sort of at least) it'd be awesome!

Although I don't have the file on my drive... ah, the annoyances of windows @ school...
